### ISSUE TITLE
traceback when removing a machine

### ISSUE THREAD

**Issue by neoclust** [pulse-project/pulse2#225]
2018-01-15 15:20:12,808 #140493920597760 ERROR Error during render base.delComputer: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/mmc/agent.py", line 251, in _putResult
    result = f(*args, **kwargs)
  File "plugins/base/__init__.py", line 2552, in delComputer
    ComputerManager().delComputer(ctx, uuid, backup)
  File "/usr/lib/python2.7/dist-packages/mmc/plugins/base/computers.py", line 281, in delComputer
    instance.delComputer(ctx, uuid, backup)
  File "/usr/lib/python2.7/dist-packages/mmc/plugins/glpi/computers.py", line 248, in delComputer
    return self.glpi.delMachine(uuid)
  File "/usr/lib/python2.7/dist-packages/mmc/plugins/glpi/database_91.py", line 3890, in delMachine
    r = requests.get(url, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'localhost' doesn't match 'demopulse.siveo.net'

**Comment by neoclust** [comment]
we need to change the installer to fix the URL of the webservice
